### ISSUE TITLE
Latest revision doesn't work

### ISSUE THREAD

**Issue by philp** [starfishmod/jquery-oembed-all#11]
Looks like something has gone astray in recent revisions, and the code simply won't work. Reverted to an earlier revision and all worked fine.

**Comment by adampatterson** [comment]
Same :(

jquery.oembed.js:182Uncaught SyntaxError: Unexpected token ,

**Comment by starfishmod** [comment]
Ok I will look into this very soon. I have been away and I have just got back.

**Comment by elranu** [comment]
Hoping you can fix it soon :)

**Comment by starfishmod** [comment]
Seems I really stuffed that last release badly. It now works in my test system. If someone can reconfirm I will close this bug

**Comment by adampatterson** [comment]
I no longer get the `jquery.oembed.js:182Uncaught SyntaxError: Unexpected token` error

**Comment by elranu** [comment]
In your demo page (http://starfishmod.github.com/jquery-oembed-all/)  now I'm getting the following error when I paste a link like this http://vimeo.com/3108686:

Uncaught TypeError: Cannot call method 'match' of undefined
$.fn.oembed.OEmbedProvider.matchesjquery.oembed.js:305
$.fn.oembed.getOEmbedProviderjquery.oembed.js:278
$.fn.oembedjquery.oembed.js:33
e.extend.eachjquery.min.js:16
e.fn.e.eachjquery.min.js:16
$.fn.oembedjquery.oembed.js:17
(anonymous function)/jquery-oembed-all/:16
f.event.handlejquery.min.js:17
f.event.add.i.handle.k

**Comment by starfishmod** [comment]
Ok I have made a fix and this now works on that screen :)

**Comment by elranu** [comment]
great!! thanks! now works perfectly :)
