### ISSUE TITLE
Any reason why you do not depend on an actual oEmbed response from provider?

### ISSUE THREAD

**Issue by jayarjo** [starfishmod/jquery-oembed-all#120]
Why don't you use an actual `html` property from oEmbed response to generate html structure to embed?

**Comment by starfishmod** [comment]
When I wrote this (quite sometime ago) most oembed providers did not provide a html embed code. Those that did often tried to embed scripts (off the top of my memory) which just didn't work.

I would imagine quite a bit has changed since then :-)

**Comment by jayarjo** [comment]
Maybe it did and maybe not :) I will probably write pure javascript version of this depending on provider code only. Will be interesting to test if it got any better.

Thanks for your response.
