### ISSUE TITLE
support aparat.com

### ISSUE THREAD

**Issue by mohsen** [starfishmod/jquery-oembed-all#121]
Provider code for aparat.com:

    new $.fn.oembed.OEmbedProvider("aparat", "video", ["aparat\\.com/v/.+"], 'http://www.aparat.com/video/video/embed/videohash/$1/vt/frame', {
        templateRegex:/.*\/v\/([a-zA-Z0-9]+).*/,embedtag: {tag: 'iframe',width: '425',height: '349'}, nocache:1
    })

**Comment by starfishmod** [comment]
Sorry I am no longer maintaining this plugin and I am only leaving it here for prosperity
