### ISSUE TITLE
flickr ,yfrog images are not coming

### ISSUE THREAD

**Issue by basker** [starfishmod/jquery-oembed-all#13]
when i post flickr and yfrog links with any text ,for example 
"test http://www.flickr.com/photos/56880511@N04/6773842530/"

like that image is not coming if i post

"http://www.flickr.com/photos/56880511@N04/6773842530/"
image is coming

**Comment by starfishmod** [comment]
I tried that particular link directly and got:
Connection refused

That is probably why this won't embed - can you provide another link that works when going directly but won't embed?

**Comment by basker** [comment]
From that content:http://www.flickr.com/photos/56880511@N04/6773842530/   image is coming

but when i add  some text to that url  for example content : hi i am basker http://www.flickr.com/photos/56880511@N04/6773842530/

then image is not coming

**Comment by basker** [comment]
if i give a link of flickr it is working but  if i add some text to link then image is not coming

**Comment by starfishmod** [comment]
I'm sorry I really can't see this issue can you show some example code/website where this happens?

**Comment by starfishmod** [comment]
Closing this issue as I can't replicate - please reopen if you can provide more samples/ example code - thanks.
