### ISSUE TITLE
Request: Dribbble

### ISSUE THREAD

**Issue by taitems** [starfishmod/jquery-oembed-all#17]
Not sure if this is the best place to submit requests, but dribbble player cards and individual shots would be good. First thing I thought of trying this script with and no dice.

**Comment by starfishmod** [comment]
Hadn't heard of dribble before this - and yes this exactly the right place for this :) I have just got it to display the image - I'm not sure I understand dribble's model exactly to put anything else in. By all means feel free to fork and improve :)
