### ISSUE TITLE
custom height and width for yql embed sites

### ISSUE THREAD

**Issue by param-veer** [starfishmod/jquery-oembed-all#18]
hello  , first of all thank you for forking this plugin and there are few websites such as youtube, minoto-video,ustream ,etc all using YQL embed in this plugin and they have thier own height and width . can u please make a option to specify a custom height and width for them , as it looks very odd with videos of same providers with different height width in  a page.

**Comment by starfishmod** [comment]
I agree this is important - I will work on this over the next few days - unless someone wants to send in a patch :P

**Comment by param-veer** [comment]
hi andrew , 

 thanks for replying me . well u did a great job yet making this plugin live again . its a very useful plugin. ill try too to find out how to make its height and width custom and help you ,

**Comment by param-veer** [comment]
hello andrew , is there a way i can contact you , m very pleased to let you know that i am about to use your forked version of jquery oembed in my new social networking website i am making . i think you fixed that height and width issue for the yql supported websites . its running awesome . thanks

**Comment by starfishmod** [comment]
You're welcome :) Please let know where you are using this toll I'd be interested to know :)

**Comment by param-veer** [comment]
yes andrew as soon as the website is ready to be online ill surly inform you , ill be glad if u help me out with this plugin with a custom height and width for yql query and all the other websites which the plugin have an individual height and width option , thanks already for forking such a good plugin and making it the best :)
