### ISSUE TITLE
Soundcloud support

### ISSUE THREAD

**Issue by gmw00** [starfishmod/jquery-oembed-all#22]
This Link does show the Album Art and some information. Is it possible to show the soundcloud player instead?
http://snd.sc/xoapBk

The full link for this does not convert at all:
http://soundcloud.com/super_pilot/sets/songs-for-dogs-super

**Comment by starfishmod** [comment]
ok there seems to be a couple of issues here :)
1. I didn't have the lookup for the shorten snd.sc urls in the list of urls to look at and it was falling back OGP support - I will add this
2. not sure why soundcloud rejects the oembed for the links given. If I try http://snd.sc/IHzxlH (http://soundcloud.com/historionyx) this works for me. The oembed response from soundcloud is 403 forbidden for the links you provided, and you will need to take this up with soundcloud.
