### ISSUE TITLE
Github images no longer working

### ISSUE THREAD

**Issue by FiXato** [starfishmod/jquery-oembed-all#26]
The GitHub icons used in the CSS no longer work as they yield a 404:
http://github.com/images/icons/public.png
http://github.com/images/modules/pagehead/actions_fade.png
http://github.com/images/modules/pagehead/repostat_watchers.png
http://github.com/images/modules/pagehead/repostat_forks.png

This is might due to their switch to Octicat icons.

**Comment by starfishmod** [comment]
I have replaced with text that kind of looks simial to the icons - not the best idea - but a bit more reliable...
