### ISSUE TITLE
Fix for normal  text.

### ISSUE THREAD

**Issue by ghost** [starfishmod/jquery-oembed-all#27]
Hi, i have replaced this line

resourceURL = (url != null) ? url : container.attr("href"),

with this:

resourceURL = (!url.indexOf('http://')) ? url : container.attr("href"),

at line 20, because this script also add href attr to normal text. With my fix work fine :)

**Comment by w8tcha** [comment]
with that fix secured links no longer work.

It should be 

resourceURL = (url && !url.indexOf('http://') || !url.indexOf('https://')) ? url : container.attr("href"),

**Comment by ghost** [comment]
Oh, ye, nice :)

**Comment by starfishmod** [comment]
Ok thanks for that - have added and will upload soon
