### ISSUE TITLE
twitiv not working because of new short url thing added in script

### ISSUE THREAD

**Issue by param-veer** [starfishmod/jquery-oembed-all#28]
hey http://twitvid.com/STOKX is not working because of the new short url thing added in the script , i request u to please look in to this friend and instead of that can u please help with the custom with of yql embeds

**Comment by param-veer** [comment]
hulu.com videos are also not working . and might be that some more would not work , friend the short url thing is crapping up the whole code. i request you to please look into it.

**Comment by starfishmod** [comment]
This is fixed I believe - please reopen if you are still having issues
