### ISSUE TITLE
Add wmode transparent to youtube embed (inside the iframe)

### ISSUE THREAD

**Issue by mrdoinel** [starfishmod/jquery-oembed-all#3]
Hello 

thanks for this wonderful plugin. :)
It work like a charm but I need to have the youtube video playing with wmode=transparent.
Is there a way to do this ?

Cheers

**Comment by mrdoinel** [comment]
Actually I found a way to achieve this by adding "?wmode=transparent" in the src :

new $.fn.oembed.OEmbedProvider("youtube", "video", ["youtube\.com/watch.+v=[\w-]+&?"],null,
      {templateRegex:/._v\=([\w-]+)&?._/
      ,embedtag : {tag: 'iframe', width:'530',height: '328',
        src: "http://www.youtube.com/embed/$1?wmode=transparent",
        }
      })

**Comment by starfishmod** [comment]
Thanks for the heads up! I have added the change on the URL.
