### ISSUE TITLE
Embedding gists not working.

### ISSUE THREAD

**Issue by elving** [starfishmod/jquery-oembed-all#31]
When I try to embed a gist (e.g https://gist.github.com/1321768) the embed code seems to be incomplete or broken.

**Comment by starfishmod** [comment]
I just tried this and it worked for me. Can you try again and tell me what the result is?

**Comment by elving** [comment]
I tried this gist (https://gist.github.com/1321768) but it only gets the title and the first paragraph:

http://jsfiddle.net/x3NaN/

![Result](http://f.cl.ly/items/1K0g2Z0K320d3J1N0738/Screen%20Shot%202012-06-20%20at%208.54.54%20PM.png)

**Comment by starfishmod** [comment]
Yes that is all github gist oEmbed result returns. You might have to take it up with github to return more information. Sorry there is not more I can do on this :(
