### ISSUE TITLE
Getting a 403 forbidden back

### ISSUE THREAD

**Issue by Kifah** [starfishmod/jquery-oembed-all#32]
hi,

i keep getting following errors on my image links:

<pre>
api.embed.ly/1/oembed?format=.............(url of img)
Failed to load resource: the server responded with a status of 403 (Forbidden)

</pre>

the funny thing, it works sometimes, and fails most of the time.

here is my javascript code:

<pre>
function newEmbedly(){

    $('.oembed').oembed(null,{
        embedMethod: 'auto',
        maxHeight: 300,
        maxWidth:450

    });

}

</pre>

**Comment by starfishmod** [comment]
can you give me the full link so I can check it out?

**Comment by iMattPro** [comment]
embed.ly is a paid service. if you are using it w/o paying, they limit the amount of times you can actually make a request through them each month. You may just be exceeding it, which may be why it sometimes works and then doesn't.
