### ISSUE TITLE
Case sensitive url

### ISSUE THREAD

**Issue by 0x0ece** [starfishmod/jquery-oembed-all#53]
This link isn't embedding:
http://Soundcloud.com/timwilliam
while the lowercase is:
http://soundcloud.com/timwilliam

From a very quick check into the code, it seems you're using case insensitive regexp, so it should be something more subtle!?

**Comment by starfishmod** [comment]
This seems to be an issue with soundcloud.. not sure but library sends the request to soundcloud and then soundcloud dies

if I do http://www.youtube.com/watch?v=xxxxx and http://www.YoUtuBe.com/watch?v=xxxxxxx
it works as expected.

I suggest following this up with soundcloud.
