### ISSUE TITLE
Youtube embeds video thumbnails?

### ISSUE THREAD

**Issue by omarvelous** [starfishmod/jquery-oembed-all#54]
Not sure if I'm doing something wrong, but URLs from youtube are returning the Video thumbnail?? Can also be seen on your demo page.

**Comment by ivirabyan** [comment]
This is because of theese lines: https://github.com/starfishmod/jquery-oembed-all/blob/master/jquery.oembed.js#L430-L432
I don't know why it's there, but this feels like a dirty hack

**Comment by starfishmod** [comment]
This is now fixed - sorry for not getting back to you sooner.
