### ISSUE TITLE
StockTwits (chart.ly changes)

### ISSUE THREAD

**Issue by adamtoth** [starfishmod/jquery-oembed-all#56]
Chart.ly has kind of moved to stocktwits links now. I added the following to be able to get a chart from a stocktwits url:

```
new $.fn.oembed.OEmbedProvider("chart.ly", "photo", ["chart\\.ly/[a-z0-9]{6,8}"], "http://chart.ly/uploads/large_$1.png?",
  { templateRegex: /.*ly\/([^\/]+).*/, embedtag: { tag: 'img'} }),
new $.fn.oembed.OEmbedProvider("stocktwits.com", "photo", ["stocktwits\\.com/message/.+"], "http://charts.stocktwits.com/production/original_$1.png?",
  { templateRegex: /.*message\/([^\/]+).*/, embedtag: { tag: 'img'} }),
```

You can use this url as an example: http://stks.co/jFTr

I also added the tiny version "stks.co" to the array at the top.

This new provider pulls in the image just fine (however it is usually blurry because it has been resized down)), but I would love it if the image linked to the original stocktwits message, or would open a lightbox to the larger sized image, or if it was possible to embed the stocktwits message similar to a twitter status update, or ideally both (displays the image, and the full stocktwits message).

**Comment by adamtoth** [comment]
It would also be cool to support stocktwits videos.

http://stks.co/nEt1

http://stocktwits.com/10609309/message/10609309

&lt;object classid='clsid:d27cdb6e-ae6d-11cf-96b8-444553540000' codebase='http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,115,0' width='560' height='345'&gt;&lt;param name='movie' value='http://stocktwits.com/screenr/player.swf' &gt;&lt;param name='flashvars' value='vSourceLink=http://stocktwits.com/10609309/message/10609309&vWidth=1580&vHeight=754&vDuration=200000&vUrl=http://videos.stocktwits.com/production/6d754200-1478-0130-4784-782bcb23b296.mp4&vImage=' &gt;&lt;param name='allowFullScreen' value='true' &gt;&lt;embed src='http://stocktwits.com/screenr/player.swf' flashvars='vSourceLink=http://stocktwits.com/10609309/message/10609309&vWidth=1580&vHeight=754&vDuration=200000&vUrl=http://videos.stocktwits.com/production/6d754200-1478-0130-4784-782bcb23b296.mp4&vImage=' allowFullScreen='true' width='560' height='345' pluginspage='http://www.macromedia.com/go/getflashplayer' &gt;&lt;/object&gt;

**Comment by starfishmod** [comment]
OK I tried to add the stocktwits line, however it doesn't work when it is a movie :( and there isn't really a way to tell from the url which it's going to be. If I leave it to use OGP it will at least show something in all cases. I did add the shortened url however.

Thanks
