### ISSUE TITLE
Chrome and https

### ISSUE THREAD

**Issue by 0x0ece** [starfishmod/jquery-oembed-all#57]
Hi,

using Chrome on a https site, the browser refuses to open connections to http, which means most of the contents can't be embedded. Example instagram, whose api is http://api.instagram... 

The best solution IMHO is to replace http://api.instagram... with //api.instagram...
However I'm not sure that _all_ services actually have an https endpoint... and I don't know any good way to test it.

Best,

**Comment by starfishmod** [comment]
I'll be happy to do that for any endpoint that supports both - as I work on this if I find an endpoint that supports both I'll change it.
