### ISSUE TITLE
how to set wmode transparent for youtube

### ISSUE THREAD

**Issue by cometta** [starfishmod/jquery-oembed-all#65]
hello,
 when using provider "youtube", using useYQL,  how to set  wmode to transparent ?

new $.fn.oembed.OEmbedProvider("youtube", "video", ["youtube\.com/watch.+v=[\w-]+&?", "youtu\.be/[\w-]+"], 'http://www.youtube.com/oembed', {useYQL:'json'}),

**Comment by starfishmod** [comment]
Ok I have made a new commit that hopefully fixes youtube (it is now an iframe instead of oembed) can you tell me if this fixes your issue?

**Comment by cometta** [comment]
sorry. it working fine now. thank you.
