### ISSUE TITLE
IE9 permission denied embedding bandcam

### ISSUE THREAD

**Issue by djculex** [starfishmod/jquery-oembed-all#7]
When using bandcam IE gives permission denied error. FF, Opera, Crome works fine..

I solved by changing line 442

return results.meta ? '<iframe width="400" height="100" src="' + results.meta.content + '" allowtransparency="true" frameborder="0"></iframe>' : false;

to
return results.meta ? '<embed type="application/x-shockwave-flash" allowfullscreen="true" menu="false" src="' + results.meta.content + '" allowtransparency="true" width="400" height="100" frameborder="0"></embed>' : false;

P.S great script :-)

**Comment by starfishmod** [comment]
I have just put in your fix - thanks very much for the fix!

**Comment by djculex** [comment]
You're welcome. Glad to help. Awesome plugin you have there.

Den 28-12-2011 02:21, Andrew skrev:
