### ISSUE TITLE
vimeo , flickr not working

### ISSUE THREAD

**Issue by cometta** [starfishmod/jquery-oembed-all#9]
hi, i try jQuery('#testelement').oembed("http://vimeo.com/33587202");

,but not working.  yes. youtube is working

**Comment by adampatterson** [comment]
I can confirm that Vimeo is not working.

Flickr did.

The Vimeo API call goes to http://vimeo/.com/api/oembed.json and when I remove the slash after vimeo it seems to work when accessing the call directly in the browser.

**Comment by adampatterson** [comment]
Vimeo and Flickr both work :)
